### ISSUE TITLE
error in parsing of the default option

### ISSUE THREAD

**Issue by g-torr** [faryabiLab/AnnoSpat#1]
I have tried to run Annospat, I find this  error (IndexError: list index out of range
), which apparently is caused by the formatting of default option for the threshold ( option -t)
![image](https://github.com/faryabiLab/AnnoSpat/assets/17313293/cc695c39-0740-4a4a-b353-097f302b10a7)
If the code works normally for you, could you add a minimum working example to the repository please?

**Comment by smith6jt-cop** [comment]
This looked like a helpful tool, but unfortunately it doesn't look like anyone is interested in providing support.  From what I can tell, the problem is line 72 calls for 3 index locations when there are only 2 from the split.  Line 62 had a list of 3 for th.  Change line 72 to:

print("IP th = ", th[0], th[1], float(th[0]), float(th[1]))

**Comment by smith6jt-cop** [comment]
Instead add extra value to 

th_str: str = typer.Option('[99.9, 99.999, **70**]', "--thresholdmaxandunknown", "-t",help=""),

**Comment by faryabib** [comment]
The postdoc developed the code with get back to you shortly.

**Comment by aanchalMongia** [comment]
Hi @g-torr and @smith6jt-cop , we apologize for a delayed response. 
Both the solutions proposed by @smith6jt-cop should work but the second one is in line with the latest implementation as well as allows us to use a single default threshold for all cell types. We have now updated the code too with the latter solution.
In our working example, the command which has been tested on our IMC T1D dataset is as follows-

AnnoSpat generateLabels -i /prefix_path/proteomix_matrix.csv -m /prefix_path/signatures.csv -outputdir -f 'HLA.ABC' -l 'Ghrelin' -r 'TIFFfilename' -t '[99.9,99.999,70]' -a '[99.5,99.5,99.5,99.5,99.9,99,99.5,99,99,99.5,99.9,99.9,99.9,99.9,99.5,99.9]' -d 'Status'
