### ISSUE TITLE
Specify input files to have an index column

### ISSUE THREAD

**Issue by smith6jt-cop** [faryabiLab/AnnoSpat#3]
Better yet, provide the expected format of protein matrix csv

**Comment by aanchalMongia** [comment]
The raw proteomics matrix is expected to be a table (.csv file) having cells on rows and proteins as columns (with dimensions= #cellsx#proteins). 
A sample marker file is placed at- AnnoSpat/data/._signatures_T1D_withImmuneCelltypes_withNegMarkers_d.csv

**Comment by cdub3575** [comment]
Hello,

I am trying to test AnnoSpat on my data, I download the sample marker file indicated but it's an empty csv, could you please provide an other example ? Do we have to put spatial coordinates in the csv ? Can we use a csv containing the information of multiple images (after a normalization step) ? 

Thank you,
Best.
