### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by smith6jt-cop** [faryabiLab/AnnoSpat#5]
Did not work with Python 3.6.15

Worked with Python 3.6.9

**Comment by aanchalMongia** [comment]
Thanks for your comment, we have updated the Readme stating "Dependencies: Python 3.6+, pip " as the code has been tested for python 3.6+ versions. 
Also, could you please elaborate on the issue you were facing with Python 3.6.15 version?

**Comment by smith6jt-cop** [comment]
The issue was an error caused by pandas deprecation of passing a set as an indexer.  When I rolled back to earlier version of python before deprecation, it solved the problem.

**Comment by aanchalMongia** [comment]
Thanks for pointing this out. 
The pandas version in the environment in which the tool was developed and has been tested is pandas==1.5.2.
